language: php
php:
  - 7.1
before_install:
  - travis_retry composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer config repositories.[GITHUB_NAME] vcs https://github.com/[GITHUB_NAME]/[PACKAGE_NAME].git
  - composer require [GITHUB_NAME]/[PACKAGE_NAME] dev-master
  - composer update
  - cp ./vendor/[GITHUB_NAME]/[PACKAGE_NAME]/tests/config/.env ./
  - rm ./config/app.php
  - cp ./vendor/[GITHUB_NAME]/[PACKAGE_NAME]/tests/config/app.php ./config
  - php artisan vendor:publish
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - php artisan migrate
  - cd ./vendor/[GITHUB_NAME]/[PACKAGE_NAME]
script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)