language: php
php:
  - 7.1
before_install:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - travis_retry composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer config repositories.shov vcs https://github.com/shov/laravel-registry.git
  - export B=master
  - composer require shov/laravel-registry dev-$B
  - composer update
  - cp ./vendor/shov/laravel-registry/tests/config/.env ./
  - rm ./config/app.php
  - cp ./vendor/shov/laravel-registry/tests/config/app.php ./config
  - php artisan vendor:publish
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - php artisan migrate
  - cd ./vendor/shov/laravel-registry
script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)